apiVersion: v1
kind: Namespace
metadata:
  name: hcl-apps
---
# ---------------- Application service Deployment ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicationservice
  namespace: hcl-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: applicationservice
  template:
    metadata:
      labels:
        app: applicationservice
    spec:
      containers:
        - name: nodejs-container
          image: santhosh0637/applicationservice:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: applicationservice
  namespace: hcl-apps
spec:
  type: LoadBalancer
  selector:
    app: applicationservice
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
# ---------------- Spring Boot Deployment ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: hcl-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: santhosh0637/orderservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: hcl-apps
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# ---------------- Node.js Deployment ----------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patientservice
  namespace: hcl-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patientservice
  template:
    metadata:
      labels:
        app: patientservice
    spec:
      containers:
        - name: nodejs-container
          image: santhosh0637/patient:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: patientservice
  namespace: hcl-apps
spec:
  type: LoadBalancer
  selector:
    app: patientservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
